name: Build and Release Mobile Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build_apk:
    name: Build Android APKs (Split)
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: 'stable'
          flutter-version: '3.44.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Remove build id
        run: sed -i -e 's/-Wl,/-Wl,--build-id=none,/' ${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}/hosted/pub.dev/jni-*/src/CMakeLists.txt

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-keystore.jks

      - name: Build Split APKs
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_PATH: release-keystore.jks
        run: flutter build apk --release --split-per-abi --split-debug-info=build/symbols

      - name: Rename APK Artifacts
        run: |
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk binqr-v${{ github.event.inputs.version }}-armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk binqr-v${{ github.event.inputs.version }}-arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk binqr-v${{ github.event.inputs.version }}-x86_64.apk

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: binqr-apk
          path: |
            binqr-v${{ github.event.inputs.version }}-armeabi-v7a.apk
            binqr-v${{ github.event.inputs.version }}-arm64-v8a.apk
            binqr-v${{ github.event.inputs.version }}-x86_64.apk

  build_aab:
    name: Build Android App Bundle
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.44.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-keystore.jks

      - name: Build App Bundle
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_PATH: release-keystore.jks
        run: flutter build appbundle --release

      - name: Rename AAB Artifact
        run: |
          mv build/app/outputs/bundle/release/app-release.aab binqr-v${{ github.event.inputs.version }}.aab

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v7
        with:
          name: binqr-aab
          path: |
            binqr-v${{ github.event.inputs.version }}.aab

  upload_to_release:
    name: Upload to GitHub Release
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [build_apk, build_aab]
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create attestation for build
        uses: actions/attest@v4
        with:
          subject-path: |
            artifacts/*.apk
            artifacts/*.aab

      - name: Release to GitHub
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
          name: binqr v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          files: |
            artifacts/*.apk
            artifacts/*.aab